# Generated by Django 4.0.3 on 2022-04-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_projectmembers_projects_lang_alter_projects_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='translations',
            name='value',
            field=models.TextField(),
        ),
    ]
