# Generated by Django 4.0.3 on 2022-04-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_website_link_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_link',
            name='language',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='website_link',
            name='link',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
