# Generated by Django 4.0.3 on 2022-04-17 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_website_link_link_alter_website_link_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='lang',
            field=models.CharField(max_length=50),
        ),
    ]
