# Generated by Django 4.0.3 on 2022-04-17 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_project_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='contributor',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
