# Generated by Django 4.0.3 on 2022-04-17 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_contributor_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectmember',
            name='language',
            field=models.CharField(default='', max_length=50),
        ),
    ]
