# Generated by Django 4.0.3 on 2022-04-26 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_projectmember_contributions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectmember',
            old_name='contributions',
            new_name='Desc',
        ),
    ]
