# Generated by Django 4.0.3 on 2022-04-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_contactoptions_contributionguidelines_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('link', models.URLField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('description', models.TextField()),
                ('language', models.CharField(default='English', max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Website_link',
            new_name='links',
        ),
        migrations.DeleteModel(
            name='ContactOptions',
        ),
        migrations.DeleteModel(
            name='ContributionGuideLines',
        ),
        migrations.DeleteModel(
            name='Contributor',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectMember',
        ),
    ]
