# Generated by Django 4.0.3 on 2022-04-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_distro_features_rename_website_link_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distro',
            name='Desc',
            field=models.TextField(default=''),
        ),
    ]
